mysite/coffeebeans/urls.py
from django.urls import path, include
from .views import CoffeeListView, CoffeeDetailView

app_name = "coffeebeans"

urlpatterns = [
    # path("", index, name="list"),
    path("", CoffeeListView.as_view(), name="list"),
    path("<int:pk>/", CoffeeDetailView.as_view(), name="details"),

    # path("<str:kind_name>/", CoffeeKindListView.as_view(), name="kind-list")
]

mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coffeebeans/', include('coffeebeans.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls'))
    )

mysite/coffeebeans/models.py
from django.db import models

class Attributes(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(blank=True, null=False)

    def __str__(self):
        return self.name


class CoffeeKind(Attributes):
    pass


class RoastLevel(Attributes):
    pass


class Origin(Attributes):
    pass


class Coffeebean(models.Model):
    name = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    kind = models.ForeignKey(CoffeeKind, on_delete=models.PROTECT, null=True)
    roast_level = models.ForeignKey(RoastLevel, on_delete=models.PROTECT, null=True)
    origin = models.ForeignKey(Origin, on_delete=models.PROTECT, null=True)
    methods = models.ManyToManyField("coffeebeans.Method")

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Coffee #{self.id} {self.name!r}>"


class Method(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=False)

    def __str__(self):
        return self.name

mysite/coffeebeans/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from django.views.generic import ListView, DetailView, DeleteView, CreateView

from .models import Coffeebean, CoffeeKind


# def index(request: HttpRequest):
#     coffees = Coffeebean.objects.select_related("kind", "roast_level", "origin").order_by("id").all()
#     context = {
#         "coffeebeans": coffees
#     }
#
#     return render(request, 'coffeebeans/index.html', context=context)

#
# def details(request: HttpRequest, pk: int):
#     coffee = get_object_or_404(
#         Coffeebean.objects.select_related("kind", "roast_level", "origin").prefetch_related("methods"),
#         pk=pk
#     )
#     context = {
#         "coffeebean": coffee,
#     }
#     return render(request, 'coffeebeans/details.html', context=context)


class CoffeeListView(ListView):
    queryset = Coffeebean.objects.order_by("id").all()
    context_object_name = "coffeebeans"
    template_name = "coffeebeans/index.html"

class CoffeeDetailView(DetailView):
    queryset = Coffeebean.objects.select_related("kind", "origin", "roast_level").prefetch_related("methods")
    context_object_name = "coffee_details"
    template_name = "coffeebeans/details.html"

mysite/coffeebeans/templates/coffeebeans/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        base title
      {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        base body
    {% endblock %}
</body>
</html>

mysite/coffeebeans/templates/coffeebeans/coffeebean_list.html
{% extends 'coffeebeans/base.html' %}

{% block title %}
    List of Coffee beans
{% endblock %}


{% block body %}
    <h1>List Of Coffee Beans </h1>
    <div>
        <ul>
            {% for coffee in object_list %}
            <li>
                <a href="{% url 'coffeebeans:details' coffee.id %}">
                    {{ coffee.name }}
                </a>
            </li>
            {% endfor %}

        </ul>
    </div>
{% endblock %}

mysite/coffeebeans/templates/coffeebeans/details.html
{% extends 'coffeebeans/base.html' %}

{% block title %}
    {{ coffeebean.name }}
{% endblock %}


{% block body %}
    <h1>{{coffeebean.name }}</h1>
    <div>
        <ul>
            <li>Kind: {{ coffeebean.kind }}</li>
            <li>Roasted level: {{ coffeebean.roast_level }}</li>
        </ul>
    <div>
    <div>
        <p> Price: {{coffeebean.price}} rub </p>
        <strong> Short description:</strong>
        <p>{{ coffeebean.description }}</p>
    </div>
    <div>
        <strong> Brewing methods:</strong>
        <ul>
            {% for method in coffeebean.methods.all %}
                <li>{{ method.name }}</li>
            {% endfor %}
        </ul>
    </div>


    <a href="{% url 'coffeebeans:list' %}">Back to list</a>
{% endblock %}

mysite/coffeebeans/templates/coffeebeans/index.html
{% extends 'coffeebeans/base.html' %}

{% block title %}
    List of Coffee beans
{% endblock %}


{% block body %}
    <ul>
        {% for coffee in coffeebeans %}
            <li>
                <a href="{% url 'coffeebeans:details' coffee.id %}">
                    {{ coffee.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}